// origins-actions-data.jsx — Plan de Acción Personalizado por esfera
// Fuente: "PILAR 2/3/4 · ACCIONES" (Especificación de Experiencia de Usuario).
// Las llaves coinciden con los nombres de esfera de SPHERE_LEVEL_TEXT / SPHERE_QUALITATIVE_MAP.

const SPHERE_ACTIONS = {
  // ── PILAR 1 · MI BASE ────────────────────────────────────────────────────
  'Autoconocimiento': {
    pillar: 'base',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu autoconocimiento. No necesitas hacerlo todo hoy. Comienza con pequeñas acciones y permite que el proceso ocurra poco a poco.',
    openingTitle: 'Antes de comenzar…',
    opening: 'No eres tus reacciones, tus miedos ni tus viejas estrategias. Muchas de ellas nacieron para protegerte. El autoconocimiento comienza cuando dejas de juzgarte y empiezas a comprenderte. Porque aquello que puedes observar, también puedes transformarlo.',
    theory: ['Daniel Kahneman', 'Aaron Beck', 'Carl Jung', 'John Bowlby', 'Gabor Maté', 'Viktor Frankl', 'James Clear', 'Robert Kegan'],
    action: [
      'Antes de reaccionar, pregúntate: ¿qué estoy sintiendo?',
      '¿Esta reacción me resulta familiar?',
      '¿Qué parte de mí está intentando protegerse?',
      'No intentes corregirte. Primero comprende.',
    ],
    habit: {
      lead: 'Al final del día dedica tres minutos a completar:',
      blanks: [
        'Hoy me sentí ____________ cuando ____________.',
        'Mi reacción fue ____________.',
        'Creo que estaba intentando proteger ____________.',
        'La próxima vez me gustaría responder desde ____________.',
      ],
      note: 'No intentes corregirte. Primero comprende.',
    },
    challenge: {
      name: 'Descubriendo mis patrones',
      lead: 'Durante siete días registra una situación emocionalmente significativa. Cada día responde:',
      steps: ['¿Qué ocurrió?', '¿Qué sentí?', '¿Cómo reaccioné?', '¿Qué necesidad o miedo estaba presente?', '¿Cómo me hubiera gustado responder?'],
      close: 'Al completar los siete días responde: hoy comprendo que muchas de mis reacciones buscan proteger ____________.',
    },
    reflection: '¿Qué parte de mí están intentando proteger mis reacciones más repetidas?',
    message: 'No eres tus reacciones, tus miedos ni tus viejas estrategias. Muchas de ellas nacieron para protegerte. El autoconocimiento comienza cuando dejas de juzgarte y empiezas a comprenderte: aquello que puedes observar, también puedes transformarlo.',
    books: [
      'Los 7 hábitos de la gente altamente efectiva — Stephen Covey',
      'Mindset — Carol Dweck',
      'Pensar rápido, pensar despacio — Daniel Kahneman',
    ],
    talks: [
      { title: 'The Power of Believing That You Can Improve', speaker: 'Carol Dweck · TED', note: 'La mentalidad de crecimiento y cómo nuestras creencias influyen en el desarrollo personal.', url: 'https://www.youtube.com/watch?v=_X0mgOOSpLU&t=22s' },
      { title: 'Herramientas para descubrir nuestra identidad', speaker: 'Alejandra Espinoza · TED', note: 'El autoconocimiento como resultado de cambiar la forma en que observamos nuestro entorno y a nosotros mismos.', url: 'https://www.ted.com/talks/herramientas_para_descubrir_nuestra_identidad' },
    ],
    capsule: 'Mi valía personal, construyendo mi confianza',
    resource: null,
  },

  'Regulación Emocional': {
    pillar: 'base',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu regulación emocional. No busques dejar de sentir: busca comprender antes de responder.',
    openingTitle: 'Antes de comenzar…',
    opening: 'Tus emociones no están en tu contra. Son señales que te ayudan a comprender qué es importante para ti, qué necesitas y qué merece tu atención. La fortaleza emocional no consiste en dejar de sentir, sino en aprender a escuchar, comprender y responder con mayor conciencia.',
    theory: [
      'James Gross — regulación emocional.',
      'Lisa Feldman Barrett — emociones construidas.',
      'Susan David — agilidad emocional.',
      'Marsha Linehan — terapia dialéctica conductual (DBT).',
      'Brené Brown — lenguaje emocional y vulnerabilidad.',
    ],
    architecture: [
      'Conciencia: desarrollar la capacidad de identificar y nombrar lo que se siente.',
      'Significado: comprender qué valor, límite o necesidad está siendo afectado.',
      'Aprendizaje: reconocer que las emociones contienen información útil sobre nosotros mismos.',
      'Acción: elegir una respuesta más consciente y coherente con nuestros valores.',
      'Identidad: construir una relación más saludable y madura con el mundo emocional.',
    ],
    action: [
      'Haz una pausa antes de reaccionar. Cuando una emoción intensa aparezca, pregúntate: ¿qué estoy sintiendo?',
      '¿Qué necesito en este momento?',
      '¿Qué puedo aprender de esto?',
      '¿Qué puedo hacer diferente?',
      '¿Quién quiero ser ante esta situación?',
    ],
    habit: {
      lead: 'Dedica tres minutos al final del día para completar:',
      blanks: [
        'Hoy me sentí ____________.',
        'Lo que más necesitaba era ____________.',
        'Esto me enseñó ____________.',
        'La próxima vez me gustaría responder con ____________.',
      ],
      note: 'El objetivo no es juzgarte, sino conocerte mejor.',
    },
    challenge: {
      name: 'Escuchar antes de reaccionar',
      lead: 'Durante siete días identifica una emoción importante cada día y responde:',
      steps: ['¿Qué me está pasando?', '¿Qué necesito?', '¿Qué puedo aprender?', '¿Qué puedo hacer diferente?', '¿Quién quiero ser ante esta situación?'],
      close: 'Al finalizar la semana pregúntate: ¿hay alguna emoción que normalmente trato de ignorar, esconder o controlar? ¿Qué cambiaría si aprendiera a escucharla en lugar de pelear con ella?',
    },
    reflection: '¿Hay alguna emoción que normalmente trato de ocultar o evitar, y qué podría cambiar en mi vida si aprendiera a escucharla con mayor comprensión?',
    message: 'Tus emociones no están en tu contra. Son señales que te ayudan a comprender qué es importante para ti, qué necesitas y qué merece tu atención. La fortaleza emocional no consiste en dejar de sentir, sino en aprender a escuchar, comprender y responder con mayor conciencia.',
    books: [
      'Inteligencia emocional — Daniel Goleman',
      'El arte de no amargarse la vida — Rafael Santandreu',
      'Tranquilos y atentos como una rana — Eline Snel',
    ],
    talks: [
      { title: 'The Gift and Power of Emotional Courage', speaker: 'Susan David · TED', note: 'Desarrollar agilidad emocional para reconocer, aceptar y gestionar las emociones sin evitarlas ni dejar que controlen nuestras decisiones.', url: 'https://www.ted.com/talks/susan_david_the_gift_and_power_of_emotional_courage' },
      { title: 'La inteligencia emocional sí se puede entrenar', speaker: 'Elsa Punset · TEDx', note: 'Cómo entrenar habilidades emocionales para responder con mayor equilibrio, empatía y autocontrol frente a los desafíos cotidianos.', url: 'https://www.youtube.com/results?search_query=Elsa+Punset+TEDx+inteligencia+emocional' },
    ],
    capsule: 'Conoce y entiende tus emociones · Regula tus emociones efectivamente',
    resource: 'Guía: "Explorando tus emociones" · Guía: "Técnicas de regulación emocional"',
  },

  'Bienestar Físico': {
    pillar: 'base',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu bienestar físico. Comienza observando tu cuerpo antes de exigirle más.',
    openingTitle: 'Antes de comenzar…',
    opening: 'Tu cuerpo es la base de todo lo que haces cada día. No es una herramienta que deba rendir sin descanso, es el lugar donde vives tu vida. Cuidarlo no es una tarea extra, es una forma de cuidarte a ti mismo.',
    theory: null,
    architecture: [
      'Cuerpo → Energía → Hábitos → Equilibrio → Bienestar sostenido.',
      'Todo comienza en el cuerpo: cuando el cuerpo está bien, la energía mejora.',
      'Cuando la energía mejora, los hábitos se vuelven más fáciles.',
      'Y cuando los hábitos son constantes, se construye un bienestar estable en el tiempo.',
    ],
    action: [
      'Observa tu cuerpo antes de exigirte más. Pregúntate durante el día: ¿cómo me siento físicamente hoy?',
      '¿Tengo energía o estoy cansado?',
      '¿Qué necesita mi cuerpo en este momento?',
      'Después elige una acción simple: descansar, moverte, hidratarte o bajar el ritmo.',
    ],
    habit: {
      lead: 'Al final del día dedica 3 minutos a revisar:',
      questions: [
        '¿Cómo estuvo mi energía hoy?',
        '¿Dormí bien?',
        '¿Me moví durante el día?',
        '¿Cómo estuvo mi nivel de estrés?',
        '¿Qué ayudó o afectó más a mi cuerpo hoy?',
      ],
    },
    challenge: {
      name: 'Observar mi cuerpo sin juzgarlo',
      lead: 'Durante 7 días enfócate en observar tu bienestar físico sin juzgarlo. Registra cada día:',
      steps: ['Horas de sueño', 'Nivel de energía (alto, medio o bajo)', 'Movimiento físico diario (sí o no)', 'Nivel de estrés (bajo, medio o alto)'],
      close: 'Al final responde: ¿qué hábitos me dan energía y cuáles me la quitan?',
    },
    reflection: '¿Estoy cuidando mi cuerpo para vivir mejor o solo lo estoy usando hasta que se agota?',
    message: 'Tu cuerpo es la base de todo lo que haces cada día. No es una herramienta que deba rendir sin descanso, es el lugar donde vives tu vida. Cuidarlo no es una tarea extra, es una forma de cuidarte a ti mismo.',
    books: [
      'Por qué dormimos — Matthew Walker',
      'El lado positivo del estrés — Kelly McGonigal',
      'El poder del movimiento — Kelly McGonigal',
      'Outlive: la ciencia y el arte de la longevidad — Peter Attia',
      'Las zonas azules — Dan Buettner',
    ],
    talks: [
      { title: 'How to Live to Be 100+', speaker: 'Dan Buettner · TED', note: 'Los hábitos de las "Zonas Azules" para vivir más y mejor: alimentación, movimiento natural, propósito y comunidad.', url: 'https://www.ted.com/talks/dan_buettner_how_to_live_to_be_100' },
      { title: 'What Makes Us Feel Good About Our Work?', speaker: 'Dan Ariely · TED', note: 'Cómo los hábitos, el bienestar y la motivación impactan la energía y la salud integral.', url: 'https://www.ted.com/talks/dan_ariely_what_makes_us_feel_good_about_our_work' },
    ],
    capsule: 'Límites saludables',
    resource: 'PDF: "Guía de autocuidado físico y mental"',
  },

  // ── PILAR 2 · MI PROPÓSITO ───────────────────────────────────────────────
  'Sentido de Vida': {
    pillar: 'proposito',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu sentido de vida. No necesitas tener todas las respuestas ni definir hoy todo tu camino. Comienza identificando qué es realmente importante para ti y observa si tus decisiones diarias te acercan a la vida que quieres construir.',
    openingTitle: 'Antes de comenzar…',
    opening: 'No necesitas tener toda la vida resuelta para comenzar a encontrar dirección. El sentido se construye cuando reconoces qué es importante para ti y empiezas a tomar decisiones más alineadas con ello. A veces no necesitas cambiar de camino, sino comprender mejor por qué quieres recorrerlo.',
    theory: [
      'Viktor Frankl — sentido de vida, significado y responsabilidad personal.',
      'Martin Seligman — bienestar, significado y construcción de una vida con propósito.',
      'William Damon — desarrollo del propósito y orientación hacia metas significativas.',
      'Edward Deci — motivación interna y decisiones vinculadas con necesidades y valores personales.',
      'Richard Ryan — autodeterminación y motivación autónoma.',
      'Stephen Covey — valores, principios, prioridades y dirección personal.',
      'Carol Dweck — aprendizaje, desarrollo personal y mentalidad de crecimiento.',
    ],
    action: [
      'Antes de tomar una decisión importante, haz una pausa y pregúntate: ¿esto me acerca o me aleja de la vida que quiero construir?',
      'Identifica qué valor es importante para ti en esa situación y elige una acción concreta que sea coherente con él.',
      'No necesitas tener todo tu camino definido; comienza haciendo que tus decisiones cotidianas reflejen lo que realmente es importante para ti.',
    ],
    habit: {
      lead: 'Al comenzar el día dedica tres minutos a completar:',
      blanks: ['Hoy es importante para mí ____________.', 'Una acción que puedo realizar para acercarme a ello es ____________.'],
      closeLead: 'Al finalizar el día pregúntate:',
      questions: [
        '¿Lo que hice hoy estuvo relacionado con algo que realmente es importante para mí?',
        '¿Qué decisión tomé por convicción?',
        '¿Qué decisión tomé solamente por obligación o presión?',
      ],
      note: 'No necesitas resolver tu propósito. Comienza observando si la forma en que vives refleja aquello que valoras.',
    },
    challenge: {
      name: 'Mi brújula interna',
      lead: 'Durante siete días observa una decisión o actividad importante de tu día. Cada día responde:',
      steps: [
        '¿Qué hice?',
        '¿Por qué lo hice?',
        '¿Fue una decisión propia o respondió principalmente a una obligación o expectativa externa?',
        '¿Qué valor importante para mí estuvo presente?',
        '¿Esta acción me acerca a la vida que quiero construir?',
      ],
      close: 'Al completar los siete días responde: ¿qué diferencia encuentro entre lo que digo que es importante para mí y la forma en que estoy viviendo?',
    },
    reflection: '¿La vida que estoy construyendo refleja realmente lo que es importante para mí?',
    message: 'No necesitas tener todas las respuestas para darle dirección a tu vida. El sentido también se construye en las pequeñas decisiones que tomas cada día. Cuando lo que haces se acerca a lo que realmente valoras, comienzas a construir una vida que se siente más tuya.',
    books: [
      'El hombre en busca de sentido — Viktor Frankl',
      'Los 7 hábitos de la gente altamente efectiva — Stephen Covey',
      'El elemento — Ken Robinson',
    ],
    talks: [
      { title: 'Los cuatro pilares para cultivar una vida con sentido', speaker: 'Emily Esfahani Smith · BBVA Aprendemos Juntos', note: 'Significado, dirección y propósito: el marco más cercano a lo que mide esta esfera.', url: 'https://aprendemosjuntos.bbva.com/especial/los-cuatro-pilares-para-cultivar-una-vida-con-sentido-emily-esfahani/' },
      { title: 'Encontrando el propósito', speaker: 'Efrén Martínez', note: 'Cómo conectar nuestras acciones con aquello que consideramos valioso.', url: 'https://www.youtube.com/watch?v=E-RYs4b3ot8' },
    ],
    capsule: 'Alineación de metas personales y profesionales',
    resource: 'Plantilla descargable: "Definición de metas SMART" + Guía PDF',
  },

  'Autónoma': {
    pillar: 'proposito',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu autonomía. Empieza por reconocer qué parte de tu situación sí depende de ti y comienza a cumplir los compromisos que haces contigo mismo.',
    openingTitle: 'Antes de comenzar…',
    opening: 'Ser autónomo no significa hacerlo todo solo ni dejar de escuchar a los demás. Significa aprender a confiar en tu criterio, tomar decisiones conscientes y asumir la responsabilidad de tus elecciones. Cada vez que cumples una promesa contigo mismo fortaleces la confianza en tu capacidad para dirigir tu propia vida.',
    theory: [
      'Edward Deci — autonomía y motivación intrínseca.',
      'Richard Ryan — autodeterminación y autonomía como necesidad psicológica.',
      'Albert Bandura — autoeficacia y confianza en la propia capacidad para actuar.',
      'Stephen Covey — proactividad, responsabilidad y toma de decisiones.',
      'James Clear — formación de hábitos, constancia y sistemas de comportamiento.',
      'Robert Kegan — desarrollo adulto y construcción progresiva de autonomía.',
      'Carol Dweck — aprendizaje, esfuerzo y capacidad de desarrollo.',
    ],
    action: [
      'Identifica una decisión o compromiso que dependa de ti y que hayas estado posponiendo.',
      'Pregúntate: ¿qué estoy esperando para actuar? ¿Qué parte de esta situación sí depende de mí?',
      'Define una acción concreta y llévala a cabo sin esperar que alguien te lo recuerde, te supervise o decida por ti. Empieza con algo pequeño que puedas cumplir.',
    ],
    habit: {
      lead: 'Al comenzar el día elige un compromiso pequeño contigo mismo. Completa:',
      blanks: ['Hoy me comprometo a ____________.', 'Depende de mí porque ____________.'],
      closeLead: 'Al finalizar el día responde:',
      questions: ['¿Cumplí la palabra que me di?'],
      note: 'Si no lo hiciste, no se trata de castigarte. Identifica qué ocurrió y decide qué puedes hacer diferente mañana.',
    },
    challenge: {
      name: 'Soy mi propio jefe',
      lead: 'Durante siete días elige una actividad que normalmente postergas o que necesitas que alguien más te recuerde. Cada día:',
      steps: [
        'Elige una tarea que dependa de ti.',
        'Decide cuándo la realizarás.',
        'Hazla sin esperar un recordatorio.',
        'Registra si la terminaste.',
        'Identifica qué facilitó o dificultó cumplirla.',
      ],
      close: 'Al finalizar la semana responde: ¿qué descubrí sobre mi capacidad para cumplir los compromisos que hago conmigo mismo?',
    },
    reflection: '¿Estoy tomando mis propias decisiones o estoy esperando que otras personas decidan, aprueben o actúen por mí?',
    message: 'Ser autónomo no significa hacerlo todo solo. Significa reconocer qué depende de ti, tomar decisiones y hacerte responsable de ellas. Cada vez que cumples un compromiso contigo mismo, fortaleces la confianza en tu capacidad para dirigir tu propia vida.',
    books: [
      'Hábitos atómicos — James Clear',
      'Los 7 hábitos de la gente altamente efectiva — Stephen Covey',
      'Mindset — Carol Dweck',
    ],
    talks: [
      { title: 'Solo existe el tomar decisiones', speaker: 'Eragdi Macias · TEDxJardinesdeSatelite', note: 'Del miedo a equivocarse a asumir la responsabilidad de elegir y avanzar.', url: 'https://www.youtube.com/watch?v=8G7t1IjKpl4' },
      { title: 'Las pequeñas decisiones moldean nuestro futuro', speaker: 'Julián García', note: 'Cómo las decisiones diarias terminan construyendo el futuro.', url: 'https://www.youtube.com/watch?v=29a2gZOKJSw' },
    ],
    capsule: 'Crea tu visión personal',
    resource: null,
  },

  'Trascendencia': {
    pillar: 'proposito',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu trascendencia. Empieza por reconocer el efecto que ya tienes en las personas que forman parte de tu vida.',
    openingTitle: 'Antes de comenzar…',
    opening: 'Lo que haces puede tener un impacto mayor del que alcanzas a ver. Una palabra, una decisión, una ayuda o algo que compartes puede hacer una diferencia en otra persona. Trascender no significa hacer algo extraordinario; comienza cuando reconoces que tus acciones también pueden contribuir al bienestar de alguien más.',
    theory: [
      'Viktor Frankl — significado, responsabilidad y orientación hacia algo que va más allá de uno mismo.',
      'Erik Erikson — generatividad, contribución y legado a otras generaciones.',
      'Martin Seligman — significado y conexión con algo mayor que uno mismo.',
      'William Damon — propósito y contribución más allá del interés personal.',
      'Christopher Peterson — fortalezas de carácter, humanidad y trascendencia.',
      'Adam Grant — ayuda, contribución y comportamiento prosocial.',
      'Abraham Maslow — desarrollo humano y autotrascendencia.',
    ],
    action: [
      'Antes de terminar el día, identifica una acción que pueda generar algo positivo en otra persona: escuchar, ayudar, compartir lo que sabes, acompañar o facilitar algo.',
      'Pregúntate: ¿qué puedo hacer hoy que también beneficie a alguien más?',
      'Realiza la acción de manera consciente y observa el impacto que genera.',
    ],
    habit: {
      lead: 'Al finalizar el día dedica tres minutos a completar:',
      blanks: ['Hoy ayudé o aporté algo a ____________.', 'Lo que hice fue ____________.', 'El impacto que pudo generar fue ____________.'],
      note: 'No busques grandes acciones. Aprende primero a reconocer el efecto que ya tienes en otras personas.',
    },
    challenge: {
      name: 'Mi rastro de impacto',
      lead: 'Durante siete días identifica una acción que haya generado algo positivo para otra persona. Cada día responde:',
      steps: ['¿Qué hice?', '¿A quién benefició?', '¿Por qué decidí hacerlo?', '¿Qué efecto tuvo?', '¿Qué aprendí de esa experiencia?'],
      close: 'Al finalizar los siete días responde: ¿qué descubrí sobre el impacto que mis acciones pueden tener en otras personas?',
    },
    reflection: '¿Qué huella estoy dejando en las personas que forman parte de mi vida?',
    message: 'Trascender no requiere hacer algo extraordinario. Muchas veces comienza en una conversación, una ayuda, una decisión o algo que compartes con alguien más. Cuando reconoces que tus acciones pueden mejorar la vida de otras personas, descubres que tu impacto puede ir mucho más allá de ti.',
    books: [
      'Dar y recibir — Adam Grant',
      'El poder del significado — Emily Esfahani Smith',
      'El hombre en busca de sentido — Viktor Frankl',
    ],
    talks: [
      { title: 'El éxito es tener un impacto positivo en los demás', speaker: 'Carlos Torres Vila', note: 'El éxito visto desde el propósito, la coherencia y la contribución.', url: 'https://www.youtube.com/watch?v=xl6tia9BAOs' },
      { title: 'Las 3 claves del impacto', speaker: 'David Samra', note: 'Herramientas para convertir la intención de ayudar en acciones concretas.', url: 'https://www.youtube.com/watch?v=s5ZK7MubMwM' },
    ],
    capsule: 'El propósito como motor: motivación y propósito',
    resource: 'Test: "¿Qué te motiva?"',
  },

  // ── PILAR 3 · MI CONEXIÓN ────────────────────────────────────────────────
  'Conexión Intrapersonal': {
    pillar: 'conexion',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer la relación que tienes contigo mismo. Empieza escuchando cómo te hablas cuando algo no sale como esperabas.',
    openingTitle: 'Antes de comenzar…',
    opening: 'La relación que construyes contigo influye en cómo enfrentas los errores, reconoces tus capacidades y tomas decisiones. Conectar contigo no significa pensar que todo está bien, sino aprender a aceptarte con honestidad, reconocer tus fortalezas y áreas de mejora y tratarte con el mismo respeto y comprensión que ofrecerías a alguien importante para ti.',
    theory: [
      'Carl Rogers — aceptación y congruencia.',
      'Kristin Neff — autocompasión.',
      'Christopher Germer — autocompasión consciente.',
      'Albert Bandura — autoeficacia.',
      'Carol Dweck — mentalidad de crecimiento.',
      'Brené Brown — vulnerabilidad y aceptación.',
      'Susan David — agilidad emocional.',
      'Nathaniel Branden — autoestima.',
    ],
    action: [
      'Cuando cometas un error o algo no resulte como esperabas, escucha cómo te hablas.',
      'Pregúntate: ¿qué me estoy diciendo? ¿Le hablaría de esta manera a alguien que quiero? ¿Qué puedo aprender de lo ocurrido sin descalificarme?',
      'Después cambia el juicio por una respuesta más útil: "Esto no salió como esperaba. ¿Qué puedo aprender y qué puedo hacer diferente?"',
    ],
    habit: {
      lead: 'Al final del día dedica tres minutos a completar:',
      blanks: [
        'Hoy reconozco en mí ____________.',
        'Hoy fui demasiado duro conmigo cuando ____________.',
        'Lo que necesitaba decirme era ____________.',
        'Mañana quiero tratarme con mayor ____________.',
      ],
      note: 'No se trata de justificarlo todo. Se trata de aprender a mirarte con honestidad sin convertir cada error en una crítica hacia quién eres.',
    },
    challenge: {
      name: 'Cómo me trato',
      lead: 'Durante siete días identifica un momento en el que hayas sido especialmente crítico contigo. Cada día responde:',
      steps: [
        '¿Qué ocurrió?',
        '¿Qué me dije?',
        '¿Cómo me hizo sentir?',
        '¿Mi forma de hablarme me ayudó a resolver la situación?',
        '¿Qué podría decirme de manera más respetuosa y útil?',
      ],
      close: 'Al finalizar responde: ¿qué patrón identifico en la forma en que me trato cuando algo no sale como espero?',
    },
    reflection: '¿La forma en que me trato me ayuda a crecer o hace que sienta que nunca soy suficiente?',
    message: 'La relación más constante de tu vida es la que tienes contigo. Puedes reconocer tus errores sin convertirlos en una definición de quién eres. Tratarte con respeto no significa dejar de exigirte; significa aprender a crecer sin estar permanentemente en tu contra.',
    books: [
      'Sé amable contigo mismo — Kristin Neff',
      'El poder de ser vulnerable — Brené Brown',
      'Los seis pilares de la autoestima — Nathaniel Branden',
    ],
    talks: [
      { title: 'Seis maneras de hablarse a uno mismo', speaker: 'Alba Cardalda · BBVA Aprendemos Juntos', note: 'Estrategias para revisar cómo nos hablamos y construir una relación interna más saludable.', url: 'https://aprendemosjuntos.bbva.com/' },
      { title: 'Autoestima y motivación: desmontando mitos', speaker: 'Roberto Colom · BBVA Aprendemos Juntos', note: 'Diferenciar el valor personal de la comparación, el rendimiento o la aprobación.', url: 'https://aprendemosjuntos.bbva.com/' },
    ],
    capsule: 'Autoestima sana',
    resource: null,
  },

  'Conexión Extrapersonal': {
    pillar: 'conexion',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer la forma en que te relacionas con los demás. Empieza por escuchar hasta el final antes de responder.',
    openingTitle: 'Antes de comenzar…',
    opening: 'Construir relaciones significativas no significa pensar igual, estar siempre de acuerdo o evitar los conflictos. Conectar con otras personas implica generar confianza, escuchar con apertura, expresar lo que piensas con respeto y aprender a convivir con perspectivas diferentes sin dejar de ser tú mismo.',
    theory: [
      'John Bowlby — apego y vínculos.',
      'Carl Rogers — empatía y escucha.',
      'Marshall Rosenberg — comunicación no violenta.',
      'Daniel Goleman — inteligencia social.',
      'John Gottman — relaciones y comunicación.',
      'Robert Waldinger — relaciones y bienestar.',
      'Brené Brown — confianza y vulnerabilidad.',
      'Jamil Zaki — empatía.',
      'Amy Edmondson — seguridad psicológica.',
    ],
    action: [
      'En una conversación importante evita preparar tu respuesta mientras la otra persona está hablando.',
      'Escucha hasta el final y pregúntate: ¿entendí realmente lo que quiso decir o estoy interpretándolo desde mi propia perspectiva?',
      'Antes de responder, resume brevemente lo que comprendiste y después expresa tu punto de vista. No necesitas estar de acuerdo para poder comprender.',
    ],
    habit: {
      lead: 'Elige una conversación al día y practica cinco minutos de presencia real: guarda el teléfono, evita interrumpir, escucha hasta el final y realiza al menos una pregunta para comprender mejor.',
      closeLead: 'Al terminar pregúntate:',
      questions: ['¿Escuché para comprender o escuché para responder?'],
    },
    challenge: {
      name: 'Conectar antes de responder',
      lead: 'Durante siete días elige una conversación significativa. Cada día registra:',
      steps: [
        '¿Con quién hablé?',
        '¿Escuché sin interrumpir?',
        '¿Pregunté antes de asumir?',
        '¿Expresé lo que pensaba con claridad y respeto?',
        '¿Qué ocurrió cuando cambié mi manera de escuchar?',
      ],
      close: 'Al finalizar responde: ¿qué hago yo que facilita o dificulta la conexión con otras personas?',
    },
    reflection: '¿Las personas importantes para mí sienten que realmente las escucho, las respeto y pueden confiar en mí?',
    message: 'Las relaciones sólidas no se construyen pensando igual. Se construyen cuando podemos hablar con autenticidad, escuchar con interés y mantener el respeto incluso cuando existen diferencias. Conectar también significa hacer espacio para que el otro pueda ser quien es.',
    books: [
      'Comunicación no violenta — Marshall B. Rosenberg',
      'Inteligencia social — Daniel Goleman',
      'El poder de ser vulnerable — Brené Brown',
    ],
    talks: [
      { title: '¿Por qué la empatía es tan importante en nuestras vidas?', speaker: 'Feggy Ostrosky · BBVA Aprendemos Juntos', note: 'Cómo la empatía influye en nuestro comportamiento social.', url: 'https://aprendemosjuntos.bbva.com/mx/especial/por-que-la-empatia-es-tan-importante-en-nuestras-vidas/' },
      { title: 'Cómo comunicarnos con asertividad', speaker: 'Estrella Montolío · BBVA Aprendemos Juntos', note: 'Hablar y escuchar como partes igualmente importantes del intercambio.', url: 'https://aprendemosjuntos.bbva.com/especial/nuestra-escritura-nos-representa-estrella-montolio/' },
    ],
    capsule: 'Asertividad emocional: comunica sin miedo ni agresión',
    resource: 'Guía para la práctica del lenguaje asertivo',
  },

  // ── PILAR 4 · MI IMPACTO ─────────────────────────────────────────────────
  'Contribución': {
    pillar: 'impacto',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu contribución. Empieza por identificar pequeñas oportunidades para sumar más allá de lo que te corresponde.',
    openingTitle: 'Antes de comenzar…',
    opening: 'Tu impacto también se construye a través de lo que aportas a los demás. Contribuir no significa hacer más por hacer más, sino utilizar tus conocimientos, habilidades y acciones para generar valor. Comienza cuando dejas de preguntarte únicamente qué tienes que cumplir y empiezas a observar qué puedes mejorar, compartir o resolver para beneficiar también a quienes te rodean.',
    theory: [
      'Adam Grant — reciprocidad y contribución.',
      'Martin Seligman — fortalezas y bienestar.',
      'Christopher Peterson — fortalezas de carácter.',
      'Amy Wrzesniewski — significado y construcción del trabajo.',
      'Jane Dutton — relaciones de alta calidad.',
      'Robert Greenleaf — servicio.',
      'Albert Bandura — agencia y autoeficacia.',
    ],
    action: [
      'Antes de terminar una tarea o participar en un proyecto, pregúntate: ¿estoy únicamente cumpliendo con lo que me corresponde o existe algo más que pueda aportar?',
      '¿Qué conocimiento, idea o acción podría facilitar el trabajo o mejorar el resultado para alguien más?',
      'Elige una aportación concreta y llévala a la práctica.',
    ],
    habit: {
      lead: 'Al comenzar el día pregúntate: ¿dónde puedo aportar valor hoy? Al finalizar completa:',
      blanks: ['Hoy contribuí cuando ____________.', 'Esto ayudó a ____________.', 'Mañana puedo aportar valor en ____________.'],
      note: 'No necesitas realizar algo extraordinario. Aprende a identificar pequeñas oportunidades para sumar.',
    },
    challenge: {
      name: 'Una aportación más',
      lead: 'Durante siete días realiza conscientemente una acción que vaya más allá de cumplir tu propia tarea: compartir conocimiento, ayudar a resolver un problema, proponer una mejora o apoyar a alguien. Cada día registra:',
      steps: ['¿Qué necesidad identifiqué?', '¿Qué aporté?', '¿A quién benefició?', '¿Qué resultado generó?', '¿Qué aprendí?'],
      close: 'Al finalizar responde: ¿qué cambia cuando dejo de pensar solamente en cumplir y comienzo a pensar también en aportar?',
    },
    reflection: '¿Las personas con las que convivo o trabajo están mejor de alguna manera gracias a lo que yo aporto?',
    message: 'Tu valor no se mide únicamente por lo que sabes o por lo que logras para ti. También se refleja en aquello que ayudas a mejorar. Cada vez que compartes, resuelves, facilitas o apoyas, conviertes tus capacidades en una contribución real.',
    books: [
      'Dar y recibir — Adam Grant',
      'El líder que no tenía cargo — Robin Sharma',
      'Descubre tus fortalezas — Marcus Buckingham y Donald O. Clifton',
    ],
    talks: [
      { title: 'El éxito es tener un impacto positivo en los demás', speaker: 'Carlos Torres Vila · BBVA Aprendemos Juntos', note: 'Cómo los valores y comportamientos se convierten en una aportación real.', url: 'https://aprendemosjuntos.bbva.com/especial/el-exito-es-tener-un-impacto-positivo-en-los-demas/' },
      { title: 'Cuando lo que se aprende en la escuela mejora tu barrio', speaker: 'Juan de Vicente Abad · BBVA Aprendemos Juntos', note: 'Convertir capacidades en acciones de servicio que resuelven necesidades reales.', url: 'https://aprendemosjuntos.bbva.com/especial/cuando-lo-que-se-aprende-en-la-escuela-mejora-tu-barrio-juan-de-vicente-abad/' },
    ],
    capsule: 'Resultados y ejecución',
    resource: 'Definición de OKRs, tablero de control de objetivos y calculadora "ROI de proyectos"',
  },

  'Liderazgo Personal': {
    pillar: 'impacto',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu liderazgo personal. Empieza por reconocer qué parte de cada situación te corresponde y actúa sin esperar autoridad formal.',
    openingTitle: 'Antes de comenzar…',
    opening: 'El liderazgo comienza mucho antes de dirigir a otras personas. Empieza en la manera en que respondes ante los retos, cumples tus compromisos, asumes tus errores y actúas cuando las circunstancias son difíciles. No necesitas un puesto o una posición de autoridad para influir: tu forma de actuar también comunica, orienta y puede convertirse en un referente para quienes te rodean.',
    theory: [
      'Albert Bandura — aprendizaje por observación y modelado.',
      'Stephen Covey — proactividad y liderazgo personal.',
      'James Kouzes y Barry Posner — liderar mediante el ejemplo.',
      'Ronald Heifetz — liderazgo adaptativo.',
      'Robert Greenleaf — liderazgo de servicio.',
      'Amy Edmondson — seguridad psicológica.',
      'Carol Dweck — mentalidad de crecimiento.',
      'Daniel Goleman — inteligencia emocional aplicada al liderazgo.',
    ],
    action: [
      'Ante un problema, antes de buscar responsables pregúntate: ¿qué parte de esta situación me corresponde?',
      '¿Qué puedo hacer yo para mejorarla? ¿Qué comportamiento quiero mostrar ante los demás?',
      'Elige una acción concreta y hazte responsable de llevarla a cabo.',
    ],
    habit: {
      lead: 'Al comenzar el día identifica una acción en la que puedas liderar con el ejemplo. Al terminar completa:',
      blanks: [
        'Hoy asumí responsabilidad por ____________.',
        'Tomé iniciativa cuando ____________.',
        'Mi comportamiento mostró ____________.',
        'Mañana quiero ser ejemplo de ____________.',
      ],
    },
    challenge: {
      name: 'Liderar sin un título',
      lead: 'Durante siete días identifica una oportunidad diaria para actuar con liderazgo sin esperar autoridad formal. Registra:',
      steps: [
        '¿Qué situación se presentó?',
        '¿Qué dependía de mí?',
        '¿Qué iniciativa tomé?',
        '¿Cómo actué frente a los demás?',
        '¿Qué resultado generó?',
      ],
      close: 'Al finalizar responde: si otras personas actuaran como yo actúo, ¿qué tipo de entorno estaríamos construyendo?',
    },
    reflection: '¿Mi forma de actuar refleja el comportamiento que espero de las personas que me rodean?',
    message: 'No necesitas que alguien te nombre líder para comenzar a liderar. Cada vez que asumes responsabilidad, tomas iniciativas y mantienes coherencia entre lo que dices y haces, estás mostrando a otros una forma de avanzar. Tu ejemplo también es una forma de influencia.',
    books: [
      'Los 7 hábitos de la gente altamente efectiva — Stephen Covey',
      'El desafío del liderazgo — James Kouzes y Barry Posner',
      'Liderazgo — Daniel Goleman',
    ],
    talks: [
      { title: 'El éxito es tener un impacto positivo en los demás', speaker: 'Carlos Torres Vila · BBVA Aprendemos Juntos', note: 'El liderazgo como capacidad de gestionarse a uno mismo y ser referente.', url: 'https://aprendemosjuntos.bbva.com/especial/el-exito-es-tener-un-impacto-positivo-en-los-demas/' },
      { title: 'Ocho pasos para ser más resiliente', speaker: 'Javier Iriondo · BBVA Aprendemos Juntos', note: 'Asumir responsabilidad, aprender del error y actuar sobre lo que sí depende de ti.', url: 'https://aprendemosjuntos.bbva.com/especial/ocho-pasos-para-ser-mas-resiliente-javier-iriondo/' },
    ],
    capsule: 'Agente de cambio: innovación y transformación',
    resource: 'Guía: cómo gestionar la resistencia al cambio · Checklist: implementación del cambio',
  },

  'Visión Estratégica': {
    pillar: 'impacto',
    intro: 'Con base en tus resultados, este es el primer paso para fortalecer tu visión estratégica. Empieza por añadir una pregunta más antes de decidir: ¿qué puede ocurrir después?',
    openingTitle: 'Antes de comenzar…',
    opening: 'Pensar estratégicamente significa levantar la mirada antes de actuar. No se trata de predecir exactamente lo que ocurrirá, sino de considerar hacia dónde quieres llegar, analizar las posibles consecuencias de tus decisiones y elegir acciones que no solo resuelvan lo inmediato, sino que también construyan mejores resultados para el futuro.',
    theory: [
      'Daniel Kahneman — juicio y toma de decisiones.',
      'Peter Senge — pensamiento sistémico.',
      'Henry Mintzberg — estrategia y aprendizaje.',
      'Michael Porter — elección estratégica.',
      'Roger Martin — pensamiento integrador.',
      'Gary Klein — decisión y anticipación.',
      'Carol Dweck — aprendizaje del error.',
      'Ari Wallach — pensamiento de largo plazo.',
    ],
    action: [
      'Antes de tomar una decisión importante, evita preguntarte únicamente "¿qué resuelve esto hoy?".',
      'Añade: ¿qué puede ocurrir después? ¿A quién puede afectar? ¿Qué problema podría generar esta decisión más adelante? ¿Existe una alternativa que resuelva lo inmediato sin comprometer el futuro?',
      'Después decide considerando tanto el presente como las posibles consecuencias.',
    ],
    habit: {
      lead: 'Elige una decisión importante del día y dedica tres minutos a pensar en tres tiempos:',
      blanks: [
        'Hoy: ¿qué necesito resolver?',
        'Después: ¿qué consecuencia puede tener?',
        'Futuro: ¿esta decisión me acerca al resultado que quiero construir?',
      ],
      note: 'Al final del día revisa si apareció alguna consecuencia que no habías considerado.',
    },
    challenge: {
      name: 'Pensar un paso adelante',
      lead: 'Durante siete días selecciona una decisión cotidiana antes de ejecutarla. Registra:',
      steps: [
        '¿Qué quiero resolver?',
        '¿Qué opciones tengo?',
        '¿Qué puede pasar con cada opción?',
        '¿Qué opción genera el mejor resultado a mediano o largo plazo?',
        '¿Qué ocurrió realmente?',
      ],
      close: 'Al finalizar responde: ¿qué cambia en mis decisiones cuando considero las consecuencias antes de actuar?',
    },
    reflection: '¿Estoy resolviendo solamente lo urgente o también estoy construyendo el resultado que quiero tener mañana?',
    message: 'No puedes controlar todo lo que ocurrirá, pero sí puedes aprender a mirar más allá de lo inmediato. Pensar estratégicamente significa tomar decisiones hoy considerando el futuro que esas decisiones pueden construir.',
    books: [
      'Pensar rápido, pensar despacio — Daniel Kahneman',
      'La quinta disciplina — Peter Senge',
      'Playing to Win — A. G. Lafley y Roger Martin',
    ],
    talks: [
      { title: 'Todo empieza por uno: identidad y planificación estratégica', speaker: 'Mariana Ponce · TED', note: 'Definir hacia dónde queremos ir y decidir para construir el futuro deseado.', url: 'https://www.ted.com/talks/mariana_ponce_todo_empieza_por_uno_identidad_y_planificacion_estrategica' },
      { title: 'Micro-decisiones, acciones conscientes y la habilidad de crear tu futuro', speaker: 'Charles Fernández · TED', note: 'Cómo las decisiones presentes y el aprendizaje del error construyen resultados futuros.', url: 'https://www.ted.com/talks/charles_fernandez_micro_decisiones_acciones_conscientes_y_la_habilidad_de_crear_tu_futuro' },
    ],
    capsule: 'Pensamiento estratégico',
    resource: 'Guía de pensamiento estratégico · Análisis DAFO personalizado',
  },
};

Object.assign(window, { SPHERE_ACTIONS });
